name: straindesign
channels:
  - conda-forge
  - plotly
  - bioconda
  - defaults
dependencies:
  - biopython
  - cameo
  - cobra<0.25.0 # https://github.com/biosustain/cameo/issues/296
  - markupsafe==2.0.1 # https://github.com/pallets/markupsafe/issues/304
  - pandas
  - plotly
  - pytest
  - python-kaleido
  - python
  - pyyaml
