{% set name = "straindesign" %}
{% set version = "3.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  build:
    - pip
    - python
    - pyyaml
    - setuptools
  run:
    - biopython
    - blessings
    - click
    - cobra>=0.24
    - escher
    - future
    - gnomic
    - inspyred
    - IProgress
    - lazy-object-proxy
    - plotly
    - python
    - markupsafe
    - networkx
    - numexpr
    - numpy<1.24 # Related to https://github.com/numpy/numpy/pull/22607
    - openpyxl
    - optlang
    - ordered-set
    - palettable
    - pandas
    - redis-py
    - requests
    - scipy
    - seaborn

test:
  imports:
    - {{ name }}
  commands:
    - python -m {{ name }} --help

about:
  home: https://github.com/brsynth/{{ name }}
  summary: Library to make metabolic engineering
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - guillaume-gricourt
