{% set name = "straindesign" %}
{% set version = "3.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  build:
    - pip
    - pytest
    - python
    - pyyaml
    - setuptools
  run:
    - biopython
    - cameo
    - cobra<0.25.0 # https://github.com/biosustain/cameo/issues/296
    - markupsafe==2.0.1 # https://github.com/pallets/markupsafe/issues/304
    - pandas
    - plotly
    - pytest
    - python-kaleido
    - python
    - pyyaml

test:
  imports:
    - {{ name }}
  commands:
    - python -m {{ name }} --help

about:
  home: https://github.com/brsynth/{{ name }}
  summary: Cli interface to predict gene knockout targets with an heterologous pathway
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - guillaume-gricourt
