name: straindesign-local
channels:
  - conda-forge
  - plotly
  - bioconda
  - defaults
dependencies:
  - biopython
  - blessings
  - click
  - cobra
  - conda-build
  - escher
  - future
  - gnomic
  - inspyred
  - IProgress
  - lazy-object-proxy
  - plotly
  - markupsafe
  - networkx
  - numexpr
  - numpy
  - openbabel
  - openpyxl
  - ordered-set
  - palettable
  - pandas
  - pytest
  - pytest-cov
  - pytest-benchmark
  - redis-py
  - requests
  - scipy
  - seaborn
