name: test
channels:
  - conda-forge
  - plotly
  - bioconda
  - defaults
dependencies:
  - biopython
  - blessings
  - click
  - cobra>=0.24
  - conda-build
  - escher
  - future
  - gnomic
  - inspyred
  - IProgress
  - lazy-object-proxy
  - plotly
  - markupsafe
  - networkx
  - numexpr
  - numpy<1.24 # Related to https://github.com/numpy/numpy/pull/22607
  - openpyxl
  - optlang
  - ordered-set
  - palettable
  - pandas
  - pytest
  - pytest-cov
  - pytest-benchmark
  - redis-py
  - requests
  - scipy
  - seaborn
