name: test
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - anaconda-client
  - biopython
  - build
  - cameo
  - cobra<0.25.0
  - markupsafe=2.0.1
  - pandas
  - pytest
  - pyyaml
