{% set name = "rpfa" %}
{% set data = load_setup_py_data() %}

package:
  name: {{name|lower}}
  version: {{data['version']}}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .

requirements:
  build:
    - pip
    - pytest
    - python
    - pyyaml
    - setuptools
  run:
    - biopython
    - cameo
    - cobrapy
    - pandas
    - pytest
    - python
    - pyyaml

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - pytest
  commands:
    - python -m {{ name|lower }} --help
    - pytest

about:
  home: https://github.com/brsynth/rpFbaAnalysis
  summary: Cli interface to predict gene knockout targets with an heterologous pathway
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - guillaume-gricourt
