{% set name = "rpfbagr" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name }}
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .

requirements:
  build:
    - pip
    - pytest
    - python
    - pyyaml
    - setuptools
  run:
    - biopython
    - cameo
    - cobrapy
    - pandas
    - pytest
    - python
    - pyyaml

test:
  imports:
    - {{ name }}
  commands:
    - python -m {{ name }} --help

about:
  home: https://github.com/brsynth/rpfbagr
  summary: Cli interface to predict gene knockout targets with an heterologous pathway
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - guillaume-gricourt
