on: ["push", "pull_request"]

name: Coverage

jobs:

  Coveralls:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: 'Install Soft'
        run: |
          pip install .
      - name: 'Install Deps'
        run: |
          pip install pytest-cov
      - name: 'Test'
        run: |
          coverage run -m pytest
          coverage lcov
      - name: 'Coveralls'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.lcov
